### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages\terminus\lib\process.js'Require stack:-...

### ISSUE THREAD

**Issue by nocoder07** [bus-stop/terminus#242] opened 2021-05-27 07:01 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [terminus](https://github.com/bus-stop/terminus) package 4.1.4

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\Coder\.atom\packages\terminus\lib\process.js'
Require stack:
- C:\Users\Coder\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:800

Error: Cannot find module 'C:\Users\Coder\.atom\packages\terminus\lib\process.js'
Require stack:
- C:\Users\Coder\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at Function.customRequire.resolve (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:5456914)
    at new Task (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:41835)
    at Function.Task.once (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:42742)
    at TerminusView.forkPtyProcess (/packages/terminus/lib/view.js:158:17)
    at TerminusView.displayTerminal (/packages/terminus/lib/view.js:170:28)
    at /packages/terminus/lib/view.js:296:14
    at /packages/terminus/lib/view.js:651:7)
    at HTMLDivElement.fn (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -5:30.6.0 core:select-all (input.hidden-input)
  9x -5:29.2.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.10.1 
terminus 4.1.4 
```

**Comment by the-j0k3r** [comment] 2021-05-27 12:28
Duplicate of #196

Please uninstall or disable platformio-ide-terminal, both shouldnt be running together ever, terminus is a modern fork of platformio-ide-terminal... 

1. Close Atom (all instances)
1. Remove `~/.atom/packages/terminus`
1. run on an external terminal `apm install terminus`
1. Open Atom profit

It works otherwise in all OS's with sane Atom installs

**Comment by the-j0k3r** [comment] 2021-09-25 14:04
No reply from @nocoder07 so closing

**Closed by the-j0k3r** 2021-09-25 14:04 UTC
Labels: duplicate :sheep::sheep:, wontfix :cry:, external :outbox_tray:
