### ISSUE TITLE
[BR] Sudo not working with the latest Atom 1.47.0

### ISSUE THREAD

**Issue by illright** [bus-stop/terminus#84] opened 2020-06-01 09:24 UTC
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [ ] I have tried uninstalling/reinstalling the terminal.
- [x] I have not tried uninstalling/reinstalling the terminal.
### Description

Looks like the latest update of Atom with its bump of Electron to 5.0.12 has caused issues with sudo in Terminus.
Funny how a similarly named piece of software, Terminus the actual emulator, has faced this issue, and seemingly overcame it: https://github.com/Eugeny/terminus/issues/960

When I run any command with sudo, I get the following output:
```
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

### Steps to reproduce

1. Open a new terminal
2. Run a command with `sudo`

**Expected behavior:**

The command should run with superuser privileges as usual

**Actual behavior:**

The command is blocked

**Reproduces how often:**

100%

### Versions

```
> atom --version
Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

```
> apm --version
apm  2.5.0
npm  6.14.5
node 14.3.0 x64
atom 1.47.0
python 3.8.3
git 2.26.2
```
OS name and version: Manjaro Linux with latest updates
Terminal version: 4.0.4

**Comment by the-j0k3r** [comment] 2020-06-01 14:28
Hi, thanks for the report. The other project you mention has nothing in common with this project, this is not a fully fledged standalone terminal.

For reference the commit that addressed that in said project is https://github.com/Eugeny/terminus/commit/98103fd1391fea8045800b8adc257fc36976f858

Im unsure if we can influence the sandbox as a plugin for Atom. Will need research.

Perhaps @UziTech has some insight?

**Comment by UziTech** [comment] 2020-06-01 14:47
Unfortunately it looks like the issue is in electron and it was fixed in v6+ but not v5
https://github.com/electron/electron/pull/19953

Not sure why the @atom team thinks it is necessary to keep Atom on an old version of Electron that isn't getting patches, but I don't think this is fixable until Atom updates to Electron v6+.

The suggestion to use [`x-terminal`](https://github.com/bus-stop/x-terminal) might work but if this is an electron issue I don't think it will.

**Comment by the-j0k3r** [comment] 2020-06-01 15:12
I can further confirm that in Earlier versions of Atom with Electron 4.2.7 the issue doesn't exist either. So the issue in electron 5.x.x is a regression.

See

![generic](https://user-images.githubusercontent.com/31389848/83423022-af02cf00-a42a-11ea-8ef6-748d19d10fae.gif)

So your option is downgrade to Atom 1.46.x and chime in to that bug report at https://github.com/electron/electron/pull/19953

**Comment by the-j0k3r** [comment] 2020-06-01 16:43
See https://github.com/atom/atom/issues/20819#issuecomment-636977765 thers nothing else to do here. Locking to contributors only to prevent me too reports.

**Comment by the-j0k3r** [comment] 2021-01-03 12:31
Now fixed upstream

**Closed by the-j0k3r** 2021-01-03 12:31 UTC
Labels: external :outbox_tray:, linux :penguin:, wontfix :cry:
