### ISSUE TITLE
Terminal not opening correctly

### ISSUE THREAD

**Issue by FueledBy-Pizza** [bus-stop/terminus#220] opened 2021-04-18 16:09 UTC
_**Windows**_ Everytime I turn on my pc, when I open a new terminal (by clicking on "+", by keybindings, or others), it just appears the blank space with the cursor, not letting me write code, neither navigate into file system. I got to uninstall the package and reinstall it again to make it work...

**Comment by merberich** [comment] 2021-04-18 20:28
Confirmed for me on Windows 10 with latest updates (OS, atom, and terminus). Uninstalling, closing atom, and reinstalling does _not_ function as a workaround for me.

**Comment by UziTech** [comment] 2021-04-18 22:11
You should only have to reinstall it once. Atom v1.56.0 updated the bundled version of node so terminus and any other package with native modules will have to be rebuilt for the new version.

**Comment by the-j0k3r** [comment] 2021-04-19 08:45
>Uninstalling, closing atom, and reinstalling does not function as a workaround for me.

It simply has to work, there is no other way around it. Do this

1. Close Atom (all instances)
1. Remove/delete `~/.atom/packages/terminus`
1. run on an external terminal `apm install terminus`
1. Open Atom profit

**Comment by mediafinger** [comment] 2021-04-19 09:47
I tried `apm rebuild` first,  
then I tried to uninstall and reinstall the terminus packaged from inside Atom,  
then I followed @the-j0k3r suggestion,  
but still, **terminus does not open a pane in Atom 1.56** for me 😿

**Comment by FueledBy-Pizza** [comment] 2021-04-19 10:03
# @the-j0k3r Solution
Followed, simply reinstalled it from the ubuntu terminal, now it works. 🙏🏼

**Comment by the-j0k3r** [comment] 2021-04-19 15:27
@mediafinger provide more information then, it works for me and most of everyone else.

For more information requested open a new issue and fill in all details requested by issue template. No exceptions.

Thx =)

**Closed** 2021-04-19 15:42 UTC
Labels: wontfix :cry:
